CC = gcc

#debug mode
connection_oriented_server: connection_oriented_server.c
	$(CC) -g connection_oriented_server.c -o connection_oriented_server

#clean
.PHONY : clean
clean:
	rm connection_oriented_server *.o