CC = gcc

#debug mode
connection_oriented_client: connection_oriented_client.c
	$(CC) -g connection_oriented_client.c -o connection_oriented_client

#clean
.PHONY : clean
clean:
	rm connection_oriented_client *.o